[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "urnc"
version = "0.0.4"
authors = [
  { name="Michael Huttner", email="michael@mhuttner.com" },
]
description = "A package to convert UR FIDS jupyter notebooks"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
  "nbconvert >= 7.2.9"
]

[project.scripts]
urnc = "urnc.convert:main"


[project.urls]
"Homepage" = "https://github.com/spang-lab/urnc"
"Bug Tracker" = "https://github.com/spang-lab/urnc/issues"
