name: Tests
on:
  push: {branches: [ main ]}
  pull_request: {branches: [ main ]}
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      JUPYTER_PLATFORM_DIRS: 1 # required to prevent deprecation warning
      UR_GIT_URL: ${{ secrets.UR_GIT_URL }}
    strategy:
      matrix:
        python-version: ['3.12']
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Test installation
      run: python3 -m pip install .
    - name: Setup test dependencies
      run: python3 -m pip install pytest pytest-cov freezegun PyYAML ipykernel
    - name: Run test suite
      run: pytest --cov=urnc --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-urnc
        fail_ci_if_error: false
